# config file version
apiVersion: 1

# list of datasources that should be deleted form the database
# deleteDatasources:
#  - name: Graphite
#    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> namde of the datasource
  - name: Prometheus
    # <string, required> datasource type
    type: prometheus
    # <string, required> acces mode. proxy or direct (Server or Browser in the UI).
    access: proxy
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> url
    url: http://prometheus:9090
    # <bool> enable/disable basic auth
    basicAuth: false
    # <bool> mark as defaul datasource. Max one per org
    isDefault: true
    # <bool> allow users to edit datasources from the UI.
    editable: true